[tools]
antigravity-cli = "latest"
bun = "latest"
claude-code = "latest"
codex = "latest"
node = "24"
opencode = "latest"
pnpm = "latest"
python = "stable"
#wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }
#usage = "latest"
#chezmoi = "latest"
#gemini = "latest"

# Mac ARM (aarch64)에서만 적용
# btop은 Homebrew 등으로 따로 설치

[tasks.bins]
description = "Show installed binaries for a package"
run = "ls -l $(mise bin-paths ${usage_package_name?})"

[tool_alias]

[tool_alias.python]

[tool_alias.python.versions]
stable = "3.13"

[settings]
activate_aggressive = true
lockfile = true
status = { missing_tools = "if_other_versions_installed" }
